#!/system/bin/sh

LOGFILE=/data/local/tmp/magiskd-helper.log

rm -f $LOGFILE
echo "Started " $(date) >> $LOGFILE
echo "-----------------------------" >> $LOGFILE
echo >> $LOGFILE
while true; do
   sleep 60
      if ! pgrep magiskd >/dev/null; then
         echo $(date) >> $LOGFILE
         echo "Magisk daemon appears to have crashed" >> $LOGFILE
         echo "Restarting magiskd..." >> $LOGFILE
         if magisk --daemon; then
            echo "success!" >> $LOGFILE
         else 
            echo "failure!" >> $LOGFILE
         fi
      echo >> $LOGFILE 
      fi	
done   
